# Generated by Django 3.0.5 on 2021-03-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table='room',
        ),
    ]
