# Generated by Django 3.0.5 on 2021-03-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210303_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listing',
            table=None,
        ),
    ]
