# Generated by Django 3.1.7 on 2021-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_danger_listingphoto_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
