# Generated by Django 3.0.6 on 2020-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('front_user', 'front_user'), ('supplier', 'supplier'), ('admin', 'admin')], default='front_user', max_length=10),
        ),
    ]
