# Generated by Django 3.0.6 on 2020-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201225_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(max_length=150, null=True, verbose_name='middle name'),
        ),
    ]
