# Generated by Django 3.0.6 on 2021-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201225_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('front_user', 'front_user'), ('admin', 'admin')], default='front_user', max_length=10),
        ),
    ]
